export const CONST_PLAID_TRANSACTIONS = [
  {
    "id": "670cf4580005ccf18f23",
    "name": "test transfer",
    "amount": "10.00",
    "date": "2024-10-14T10:37:12.936+00:00",
    "paymentChannel": "online",
    "category": "Transfer",
    "type": "debit"
  },
  {
    "id": "zNQpvEvX7RuVA3ajVQrGsnKq8893QjilNdEqB",
    "name": "Uber 072515 SF**POOL**",
    "paymentChannel": "online",
    "type": "online",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 6.33,
    "pending": false,
    "category": "Travel",
    "date": "2024-10-04",
    "image": "https://plaid-merchant-logos.plaid.com/uber_1060.png"
  },
  {
    "id": "Bp6EJgJbQ1fMR3ovMDeXfMgd44bZyEF4Mv7ZM",
    "name": "Uber 063015 SF**POOL**",
    "paymentChannel": "online",
    "type": "online",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 5.4,
    "pending": false,
    "category": "Travel",
    "date": "2024-09-21",
    "image": "https://plaid-merchant-logos.plaid.com/uber_1060.png"
  },
  {
    "id": "4xoN1g15KBiZgwVeZXzmSzXl88ELQvCJbpgke",
    "name": "CREDIT CARD 3333 PAYMENT *//",
    "paymentChannel": "other",
    "type": "other",
    "accountId": "Lm5vJzJDWnfBArJaBGQVudeppPKAQ7tkBA55L",
    "amount": 25,
    "pending": false,
    "category": "Payment",
    "date": "2024-09-21",
    "image": null
  },
  {
    "id": "33p4MDMAqzIX9vgzX3MpHEkjooJNrVIZlgwPy",
    "name": "United Airlines",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": -500,
    "pending": false,
    "category": "Travel",
    "date": "2024-09-19",
    "image": "https://plaid-merchant-logos.plaid.com/united_airlines_1065.png"
  },
  {
    "id": "xa71vZvnP9iJg1rnJZKkHDZdEEnrL6i64M9N3",
    "name": "McDonald's",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 12,
    "pending": false,
    "category": "Food and Drink",
    "date": "2024-09-18",
    "image": "https://plaid-merchant-logos.plaid.com/mcdonalds_619.png"
  },
  {
    "id": "do5v1A16pjtnM3ANnVQLcPBR66GJWoFJEyPG3",
    "name": "Starbucks",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 4.33,
    "pending": false,
    "category": "Food and Drink",
    "date": "2024-09-18",
    "image": "https://plaid-merchant-logos.plaid.com/starbucks_956.png"
  },
  {
    "id": "a15vQLQbM4HWk9XPWVMbCWkqvvdw7DiZ56RPW",
    "name": "SparkFun",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 89.4,
    "pending": false,
    "category": "Food and Drink",
    "date": "2024-09-17",
    "image": null
  },
  {
    "id": "Nl5vJ3JDGmCx3AQGxbj7h4XJLLkRepcy68rx3",
    "name": "INTRST PYMNT",
    "paymentChannel": "other",
    "type": "other",
    "accountId": "Lm5vJzJDWnfBArJaBGQVudeppPKAQ7tkBA55L",
    "amount": -4.22,
    "pending": false,
    "category": "Transfer",
    "date": "2024-09-16",
    "image": null
  },
  {
    "id": "do5v1A16pjtnM3ANnVQLcPBRpDk4G7iJANRoZ",
    "name": "Uber 072515 SF**POOL**",
    "paymentChannel": "online",
    "type": "online",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 6.33,
    "pending": false,
    "category": "Travel",
    "date": "2024-09-04",
    "image": "https://plaid-merchant-logos.plaid.com/uber_1060.png"
  },
  {
    "id": "a15vQLQbM4HWk9XPWVMbCWkqa13xdguZG4DpZ",
    "name": "Uber 063015 SF**POOL**",
    "paymentChannel": "online",
    "type": "online",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 5.4,
    "pending": false,
    "category": "Travel",
    "date": "2024-08-22",
    "image": "https://plaid-merchant-logos.plaid.com/uber_1060.png"
  },
  {
    "id": "olB4vkvnr8CmaQzym8XxuNPzVkyvjafow9b46",
    "name": "CREDIT CARD 3333 PAYMENT *//",
    "paymentChannel": "other",
    "type": "other",
    "accountId": "Lm5vJzJDWnfBArJaBGQVudeppPKAQ7tkBA55L",
    "amount": 25,
    "pending": false,
    "category": "Payment",
    "date": "2024-08-22",
    "image": null
  },
  {
    "id": "4xoN1g15KBiZgwVeZXzmSzXlyB49EoiJE5L8l",
    "name": "United Airlines",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": -500,
    "pending": false,
    "category": "Travel",
    "date": "2024-08-20",
    "image": "https://plaid-merchant-logos.plaid.com/united_airlines_1065.png"
  },
  {
    "id": "Nl5vJ3JDGmCx3AQGxbj7h4XJgEGmkWCyNZQLn",
    "name": "McDonald's",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 12,
    "pending": false,
    "category": "Food and Drink",
    "date": "2024-08-19",
    "image": "https://plaid-merchant-logos.plaid.com/mcdonalds_619.png"
  },
  {
    "id": "PK5vJdJDq9caAq41aykjuPXDrRxGvMiomdAEN",
    "name": "Starbucks",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 4.33,
    "pending": false,
    "category": "Food and Drink",
    "date": "2024-08-19",
    "image": "https://plaid-merchant-logos.plaid.com/starbucks_956.png"
  },
  {
    "id": "jGlBvKvnA1ie6KErevlZcWj48ZkqG1u6b4aow",
    "name": "SparkFun",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 89.4,
    "pending": false,
    "category": "Food and Drink",
    "date": "2024-08-18",
    "image": null
  },
  {
    "id": "gE5KoLoW8QSAmX3zAVxWum35Q4BjGDfEkD5j3",
    "name": "INTRST PYMNT",
    "paymentChannel": "other",
    "type": "other",
    "accountId": "Lm5vJzJDWnfBArJaBGQVudeppPKAQ7tkBA55L",
    "amount": -4.22,
    "pending": false,
    "category": "Transfer",
    "date": "2024-08-17",
    "image": null
  },
  {
    "id": "74E7oWoDBdFgep3zg4j1cxXZkmG5aEcdVQx46",
    "name": "Uber 072515 SF**POOL**",
    "paymentChannel": "online",
    "type": "online",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 6.33,
    "pending": false,
    "category": "Travel",
    "date": "2024-08-05",
    "image": "https://plaid-merchant-logos.plaid.com/uber_1060.png"
  },
  {
    "id": "eg5lL8LWo7cJXwe6JVgLHXlR67oNrefrnDmyx",
    "name": "Uber 063015 SF**POOL**",
    "paymentChannel": "online",
    "type": "online",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 5.4,
    "pending": false,
    "category": "Travel",
    "date": "2024-07-23",
    "image": "https://plaid-merchant-logos.plaid.com/uber_1060.png"
  },
  {
    "id": "8Nkeg8gE3au9ExpB9N3gtv8zNqyZbQfWEa8x9",
    "name": "CREDIT CARD 3333 PAYMENT *//",
    "paymentChannel": "other",
    "type": "other",
    "accountId": "Lm5vJzJDWnfBArJaBGQVudeppPKAQ7tkBA55L",
    "amount": 25,
    "pending": false,
    "category": "Payment",
    "date": "2024-07-23",
    "image": null
  },
  {
    "id": "Qr5wlalDKvcvkwKbvXMzSjNp4vyE3LuwAoDrB",
    "name": "United Airlines",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": -500,
    "pending": false,
    "category": "Travel",
    "date": "2024-07-21",
    "image": "https://plaid-merchant-logos.plaid.com/united_airlines_1065.png"
  },
  {
    "id": "ZP5XaGaWNrCvgj8rvV7LSg9e1rZldQhekLGn9",
    "name": "McDonald's",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 12,
    "pending": false,
    "category": "Food and Drink",
    "date": "2024-07-20",
    "image": "https://plaid-merchant-logos.plaid.com/mcdonalds_619.png"
  },
  {
    "id": "My5vJBJDAbf3KeEd3wl1ca4XjKEbyBhLZx1bZ",
    "name": "Starbucks",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 4.33,
    "pending": false,
    "category": "Food and Drink",
    "date": "2024-07-20",
    "image": "https://plaid-merchant-logos.plaid.com/starbucks_956.png"
  },
  {
    "id": "1z1dQDQEGKFLVbG3LzZ1ur6VEdwlAqupv7rbL",
    "name": "SparkFun",
    "paymentChannel": "in store",
    "type": "in store",
    "accountId": "1z1dQDQEGKFLVbG3LzZ1ur6eeBWmJ4FpVn11b",
    "amount": 89.4,
    "pending": false,
    "category": "Food and Drink",
    "date": "2024-07-19",
    "image": null
  },
  {
    "id": "E85GJgJD1ofAvWlEAaRXuqloQxP7a6u4dQmjG",
    "name": "INTRST PYMNT",
    "paymentChannel": "other",
    "type": "other",
    "accountId": "Lm5vJzJDWnfBArJaBGQVudeppPKAQ7tkBA55L",
    "amount": -4.22,
    "pending": false,
    "category": "Transfer",
    "date": "2024-07-18",
    "image": null
  }
]